export const SocialData=[
    {
        platform:"Facebook",
        linl:"www.instagram.com/gu_ruf",
        icon:require("../../assets/facebook.png").default
    },
    {
        platform:"Instagram",
        linl:"www.instagram.com/gu_ruf",
        icon:require("../../assets/instagram.png").default
    },
    {
        platform:"Github",
        linl:"www.instagram.com/gu_ruf",
        icon:require("../../assets/github.png").default
    },
    {
        platform:"Linkedin",
        linl:"www.instagram.com/gu_ruf",
        icon:require("../../assets/linkedin.png").default
    }
]